### ISSUE TITLE
Ansible is GPLv3 software and column is doing straight imports from it as BSD-2

### ISSUE THREAD

**Issue by dmsimard** [vmware/column#121]
Hi,

I'm no licensing expert but just wanted to point out that you are importing Ansible as a library in your software which is licensed BSD-2.
There are different instances in the Ansible documentation (like [here](http://docs.ansible.com/ansible/latest/dev_guide/developing_modules_documenting.html#copyright))     which encourages licensing as GPL when importing or extending Ansible.

**Comment by kars7e** [comment]
Thanks for bringing that to our attention, we will re-evaluate that internally and change the license if needed.

**Comment by kars7e** [comment]
Column has been re-licensed under GPLv3 via https://github.com/vmware/column/pull/143 and https://github.com/vmware/column/pull/141. Again, thanks for letting us know!
