### ISSUE TITLE
tags not working

### ISSUE THREAD

**Issue by WenwuPeng** [vmware/column#130]
Just file this issue to tracking  tags not working,  it will run all ansible task not the task is tagged

code snip:
only_tags = ['prep']
status = conn.create_run(
            site_file,
            host_file,
            self._user,
            self._password,
            self._pvt_key_file,
            extra_vars=extra_vars if extra_vars else {},
            subset=limit_hosts,
            tags=only_tags if only_tags else 'all',
            verbosity=4 if self._verbose else 0
        )

**Comment by ericwb** [comment]
Fixed with pull request #137
