### ISSUE TITLE
Column needs a way to cancel/stop a run

### ISSUE THREAD

**Issue by ericwb** [vmware/column#131]
Column needs a way to stop a run.  If I'm able to start a run, there needs to be an equal way to cancel one.

**Comment by ericwb** [comment]
I think an appropriate API would be:

DELETE on /runs/{run_id}

**Comment by ushergod** [comment]
My concert is that killing a thread will lead deadlock to our service.

**Comment by ericwb** [comment]
Fixed with pull request #140
