### ISSUE TITLE
When using the container, no column.log is generated

### ISSUE THREAD

**Issue by fredvong** [vmware/column#149]
**In column/api/run.py**
if os.access(LOG_FILE, os.W_OK):
    logging.basicConfig(filename=LOG_FILE,
                        format='%(asctime)s %(levelname)s '
                               '%(name)s %(message)s',
                        level=LOG_LEVEL)

if /var/log/column/colume.log does not exists, no long is generated.

**Dockerfile**
I need to add the following in order to make the log works.
mkdir -p /var/log/column \
&& touch /var/log/column/column.log

**Comment by ericwb** [comment]
Fixed with Pull Request #150
