### ISSUE TITLE
Strip passwords, keys, etc out of run list

### ISSUE THREAD

**Issue by ericwb** [vmware/column#157]
When using the API to list the runs, the response contains data that really shouldn't be part of it.  It should really strip out:

- private_key_file
- conn_pass
- become_pass
- remote_user
- verbosity

I think the most important to have included are:

- id
- inventory_file
- state
- playbook_path

`[{u'inventory_file': u'hosts.ini', u'id': u'b0b875d1-b59c-4ee9-a009-9e9c393cf6fe', u'state': u'COMPLETED', u'playbook_path': u'support-db.yml', u'progress': 1, u'options': {u'subset': None, u'remote_user': u'user', u'tags': u'all', u'extra_vars': {}, u'verbosity': 0, u'private_key_file': u'id_rsa', u'become_pass': u'***', u'conn_pass': u'***'}}]`

**Comment by ericwb** [comment]
The `conn_pass` and `become_pass` are always masked, so I don't see any value in those being in the response.  Also, it would be wise to strip out `private_key_file` since this is a sensitive file.

**Comment by ushergod** [comment]
https://github.com/vmware/column/pull/158
