### ISSUE TITLE
A RESTful service in column

### ISSUE THREAD

**Issue by kars7e** [vmware/column#21]
This is a catch-all issue to describe the overall goals of RESTful service in Column. It can also serve as a place to discuss the needs. We eventually may want to create issues dedicated to different subfeatures of the service.

**Goals:**

- A standalone service that exposes HTTP-based API to run Ansible playbooks.
- API consumes and produces payload in JSON format.
- API gives a way to specify which playbook to execute, which variables to include, and which hosts (inventory) to run playbook against.
- service is capable of executing multiple playbooks at the same time.

**Open Questions & problems:**

- Do we want to persist the existence of playbook execution?
-- If service is restarted, does it retain the information about what was being executed before restart?
-- If service is restarted, does it retain the information which task/playbook was executed last when it was interrupted?
- How do we store playbook files? How does service know where to look for them?
- How do we provide inventory? Can we specify it in the JSON payload? What is the format? How do we work around the Ansible expectation of INI-like syntax for inventory?
- When playbook sets some facts, and the same playbook is executed later without restarting service, These facts remain set. We need to clean the internal state between playbook execution and ensure isolation for executions that take place at the same time.
- Error handling: we need a way to catch & retrieve errors that may arise during playbook execution so that later they can be returned via REST API. We could do this by utilizing callbacks mechanism.
- Logging: We should catch ansible output and log it in some log-friendly format. We could also add a web socket API to stream logs for playbook execution (stretch goal).
- Secrets management:
-- How do we store private SSH keys?
-- How do we store passwords & other secrets that may be used in playbooks?

**Comment by ushergod** [comment]
**How do we store playbook files?** 


My first mind is to have filesystem api in our backend.(we may use existing framework), and also we can just keep same structure as we have now. (if there is better and efficient structure, we could discuss more)
```
project/
    site.yml
    ....
    role/
        etc/
        template/
        tasks/
        meta/
        files/
        ...
```

If I understand correctly, 
the process for playing playbook:
We may need to do a POST action for metadata of the playbook files and then POST action for uploading the all necessary playbook files and (column api service will take care the association). 

One more question is how could we get the playbook path?
given we know the project and startpoint( in common case, it would be site.yml). column api can easily identify the location of the playbooks by talking to filesystem framework.

**Comment by kars7e** [comment]
I think uploading files might be an overkill. For now, we can just specify the path to playbooks via config variable in service config file. The main goal is to be able to run different playbooks remotely, but those playbooks will usually stay the same. Once we have the path to playbooks configured in config file, we can then figure out the actual path to particular playbook by concatenation (keeping in mind the edge cases when someone specifies '../' in their playbook path).
